/*
 * Swagger hierarchy
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for NodesApi
 */
@Ignore
public class NodesApiTest {

    private final NodesApi api = new NodesApi();

    
    /**
     * Create a node
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNodesTest() throws ApiException {
        
        api.createNodes();

        // TODO: test validations
    }
    
    /**
     * List all nodes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNodesTest() throws ApiException {
        
        Integer limit = null;
        
        List response = api.listNodes(limit);

        // TODO: test validations
    }
    
    /**
     * Info for a specific node
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showNodeByIdTest() throws ApiException {
        
        String nodeId = null;
        
        List response = api.showNodeById(nodeId);

        // TODO: test validations
    }
    
}
